name: pubviz
author: Kevin Moore <kevmoo@google.com>
version: 1.1.0+1
homepage: https://github.com/kevmoo/pubviz
description: Visualize package dependencies in your Dart project
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  collection: '>=0.9.0 <1.0.0'
  path: '>=1.0.0 <2.0.0'
  yaml: '>=0.9.0 <0.10.0'
