name: pubviz
author: Kevin Moore <kevmoo@google.com>
version: 2.1.1-dev
homepage: https://github.com/kevmoo/pubviz
description: Visualize package dependencies in your Dart project
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0+1 <0.12.0'
  collection: '>=0.9.0 <1.0.0'
  path: '>=1.0.0 <2.0.0'
  yaml: '>=2.0.0 <3.0.0'
dev_dependencies:
  hop: '>=0.30.0 <0.32.0'
