name: pubviz
version: 1.0.0
author: Kevin Moore <kevin@thinkpixellab.com>
description: Visualize package dependencies in your Dart project
homepage: https://github.com/kevmoo/pubviz
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  path: '>=0.9.0 <0.10.0'
  unmodifiable_collection: '>=0.9.0 <0.10.0'
  yaml: '>=0.9.0 <0.10.0'
