name: pubviz
version: 2.4.3-dev
author: Kevin Moore <kevmoo@google.com>
description: Visualize package dependencies in your Dart project
homepage: https://github.com/kevmoo/pubviz

environment:
  sdk: '>=2.0.0-dev.48 <2.0.0'

dependencies:
  args: ^1.4.1
  build_cli_annotations: ^0.1.2
  collection: ^1.0.0
  gviz: ^0.2.0
  http: ^0.11.1+3
  io: ^0.3.2+1
  path: ^1.0.0
  pub_semver: ^1.0.0
  stack_trace: ^1.6.0
  yaml: ^2.0.0

dev_dependencies:
  build_cli: ^0.2.1
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+2
  js: ^0.6.1
  test: ^0.12.0
  test_descriptor: ^1.0.3
  test_process: ^1.0.1

executables:
  pubviz: null
