name: pubviz
version: 0.1.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Visualize package dependencies in your Dart project
homepage: https://github.com/kevmoo/pubviz
environment:
  sdk: '>=0.6.20'
dependencies:
  path: '>=0.6.20'
  unmodifiable_collection: '>=0.6.20'
  yaml: '>=0.6.20'
