name: pubviz
author: Kevin Moore <kevin@thinkpixellab.com>
version: 1.1.0
homepage: https://github.com/kevmoo/pubviz
sdk:
  sdk: '>=1.0.0 <2.0.0'
description: Visualize package dependencies in your Dart project
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  collection_helpers: '>=0.9.1 <2.0.0'
  path: '>=1.0.0 <2.0.0'
  yaml: '>=0.9.0 <0.10.0'
