name: pubviz
version: 2.2.0
author: Kevin Moore <kevmoo@google.com>
description: Visualize package dependencies in your Dart project
homepage: https://github.com/kevmoo/pubviz
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0+1 <0.13.0'
  collection: '>=0.9.0 <1.0.0'
  path: '>=1.0.0 <2.0.0'
  yaml: '>=2.0.0 <3.0.0'
dev_dependencies:
  hop: '>=0.30.0 <0.32.0'
  hop_git: '>=0.1.0 <0.2.0'
