name: pubviz
version: 2.2.2+1
author: Kevin Moore <kevmoo@google.com>
description: Visualize package dependencies in your Dart project
homepage: https://github.com/kevmoo/pubviz
environment:
  sdk: '>=1.9.0-dev.10 <2.0.0'
dependencies:
  args: ^0.12.1
  collection: ^1.0.0
  http: ^0.11.1+3
  path: ^1.0.0
  pub_semver: ^1.0.0
  yaml: ^2.0.0
dev_dependencies:
  hop: ^0.31.0
  hop_git: ^0.1.0
  unittest: ^0.11.5+4
executables:
  pubviz: null
